### ISSUE TITLE
Click to select should be exclusive

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalibur#43]
Is the current behavior where click-to-select adds to current selection intentional? AFAIK in all other apps, you need to hold down `ctrl`/`shift` to add to selection.

I propose we use a modifier for that.

Affinity Designer uses `Shift`. Not sure what the standard is on this.

**Comment by vjeux** [comment]
Agreed, I don't think it's intentional. I believe that usually shift is for adding, ctrl is for inverting (if selected, remove it, otherwise add).

I think that the issue is that the logic is done onmousedown where you don't have enough context to make a good decision. We'll need to check if we are clicking onmouseup and check if we haven't moved.

**Comment by dwelle** [comment]
> I think that the issue is that the logic is done onmousedown where you don't have enough context to make a good decision. 

IMO not necessary since we don't support drag-select when clicking inside an element, thus we can already determine the desired behavior in `mousedown` event, if I'm not mistaken.
